server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://114.67.72.37:3307/tensquare_base?characterEncoding=utf-8&useSSL=false
    username: root
    password: Yuanyulou789!
  jpa:
    database: mysql
    show-sql: true