server: 
  port: 9003
spring: 
  application:  
    name: tensquare-qa #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://114.67.72.37:3307/tensquare_qa?characterEncoding=utf-8&useSSL=false
    username: root
    password: Yuanyulou789!
  jpa: 
    database: MySQL
    show-sql: true
