server:
  port: 9010
spring:
  application:
    name: tensquare-friend
  datasource:   # 配置数据源
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://114.67.72.37:3307/tensquare_qa?characterEncoding=utf-8&useSSL=false
    username: root
      password: Yuanyulou789!
  jpa:
    database: mysql
    show-sql: true
jwt:
  config:
    key: itcast
    ttl: 3600000
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
