server: 
  port: 9006
spring: 
  application:  
    name: tensquare-spit #指定服务名
  data:
    mongodb:
      host: 114.67.72.37
      database: spitdb
    redis:
      host: 114.67.72.37
      port: 6379
      password: redis123456