server: 
  port: 9001
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://114.67.72.37:3307/tensquare_base?characterEncoding=utf-8&useSSL=false
    username: root
    password: Yuanyulou789!
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 114.67.72.37
    port: 6379
    password: redis123456
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true
jwt:
  config:
    key: itcast
    ttl: 3600000